import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'

export default function Home() {
  const [location, setLocation] = useState("");
  const [data, setData] = useState({});

 const axios = require("axios");

const options = {
  method: 'GET',
  url: 'https://realty-in-ca1.p.rapidapi.com/locations/auto-complete',
  params: {Area: 'British Columbia', CultureId: '1'},
  headers: {
    'X-RapidAPI-Key': '30459a32bdmsh93cc18386cfa39ap1de118jsn0077ac10a5c7',
    'X-RapidAPI-Host': 'realty-in-ca1.p.rapidapi.com'
  }
};

axios.request(options).then(function (response) {
	console.log(response.data);
}).catch(function (error) {
	console.error(error);
});



  return (
    <>
      <Head>
        <title>Current Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div>{data.location}</div>
       
      </main>

    </>
  )
}
