import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router'
import MainButton from '../components/Button'
import axios from 'axios'
import CatButton from '../components/CatButton'
import NavBar from '../components/NavBar'
import ListCard from '../components/ListCard'
import FavCard from '../components/FavCard'

export default function Home() {
  const r = useRouter();




  return (
    <>
      <Head>
        <title>Current Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
      <div style={{display:'flex'}}>
        <FavCard />

        <ListCard/>
      <MainButton
      w='135px'
      h='135px'
      src='./findanagent.png'
      iconh='70px'
      iconw='95px'
      lbltxt='Find an Agent'
      fs='16px'
      onClick={() => r.push("/findanagent")}
      ></MainButton>
      <MainButton
      w='135px'
      h='135px'
      src='./lightbulb.png'
      iconh='75px'
      iconw='80px'
      lbltxt='Tips'
      fs='16px'
      ></MainButton>
      </div>

      <NavBar></NavBar>
       
      </main>

    </>
  )
}
