import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'


export default function RealEstate() {
 
 const axios = require("axios");

const options = {
  method: 'GET',
  url: 'https://realty-in-ca1.p.rapidapi.com/locations/auto-complete',
  params: {Area: 'langley', CultureId: '1'},
  headers: {
    'X-RapidAPI-Key': '30459a32bdmsh93cc18386cfa39ap1de118jsn0077ac10a5c7',
    'X-RapidAPI-Host': 'realty-in-ca1.p.rapidapi.com'
  }
};

axios.request(options).then(function (response) {
	console.log(response.data);
}).catch(function (error) {
	console.error(error);
});



  return (
    <>
      <Head>
        <title>Current Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
      <div style={{display:'flex'}}>
      <MainButton
      w='135px'
      h='135px'
      src='./findanagent.png'
      iconh='70px'
      iconw='95px'
      lbltxt='Find an Agent'
      fs='16px'
      onClick={() => r.push("/findanagent")}
      ></MainButton>
      <MainButton
      w='135px'
      h='135px'
      src='./lightbulb.png'
      iconh='75px'
      iconw='80px'
      lbltxt='Tips'
      fs='16px'
      ></MainButton>
      </div>

      <NavBar></NavBar>
       
      </main>

    </>
  )
}
