import NavBar from "../components/NavBar";
import Heading from "../components/Heading";
import Title from "../components/Title";
import Head from "next/head";
import ProfileTab from "../components/Tab";
import Image from "next/image";

export default function Profile(){
    return(
        <>
        <Head>
        <title>RealEasy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
         <Title></Title>
        <Heading headingtxt="Profile"></Heading>

        <div style={{display:'flex', justifyContent:'center', marginBottom:30}}>
            <Image src={'/../public/avatar.png'} height={250} width={250} style={{borderRadius:'50%'}}></Image>
        </div>

        <div style={{display:'flex', justifyContent:'center'}}>
        <ProfileTab></ProfileTab>
        </div>
        <NavBar></NavBar>

        </>
    )
}